// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreparedContextResponseEvent = { 
/**
 * JSON payload of the most recently prepared Responses API request.
 */
snapshot_json: string | null, };
